/* eslint-disable */ export const DB = { token: { accessToken: "fake-token-12345789-abcdefgh", 
user: { firstname: "OSS", lastname: "", email: "oss@test.com", password: "skcc" }, }, 
customers: [ { membership: false, mobile: "555-555-555", rewards: 21, id: 2, firstname: "Larsen", lastname: "Shaw", email: "abc@test.com", avatar: "/assets/img/avatar3.png", }, 
			{ membership: false, mobile: "555-555-555", rewards: 89, id: 4, firstname: "Rosseta", lastname: "Wilson", email: "test@test.com", avatar: "/assets/img/avatar4.png", }, 
			{ membership: false, mobile: "555-555-555", rewards: 38, id: 5, firstname: "William", lastname: "Carney", email: "test@test.com", avatar: "/assets/img/avatar2.png", }, 
			{ membership: false, mobile: "555-555-555", rewards: 23, id: 6, firstname: "Sarah", lastname: "Dunne", email: "test@test.com", avatar: "/assets/img/avatar1.png", }, 
			{ membership: true, mobile: "555-555-555", rewards: 23, id: 8, firstname: "Merriana", lastname: "Sean", email: "test@test.com", avatar: "/assets/img/avatar5.png", },
			{ membership: true, mobile: "555-555-555", rewards: 26, id: 9, firstname: "Jubino", lastname: "Gerret", email: "test@test.com", avatar: "/assets/img/avatar1.png", }, 
			{ membership: false, mobile: "555-555-555", rewards: 22, id: 10, firstname: "Geneva", lastname: "Wilson", email: "test@test.com", avatar: "/assets/img/avatar2.png", }, 
			{ membership: true, mobile: "555-555-555", rewards: 38, id: 11, firstname: "Mark", lastname: "Carney", email: "test@test.com", avatar: "/assets/img/avatar5.png", }, 
			{ membership: false, mobile: "555-555-555", rewards: 27, id: 12, firstname: "Yann", lastname: "Larrel", email: "test@test.com", avatar: "/assets/img/avatar1.png", },
			{ membership: true, firstname: "John", lastname: "Doe", mobile: "555-555-555", rewards: 88, email: "john.doe@test.com", id: 13, }, 
			{ avatar: null, firstname: "sdfsdf", lastname: "sdfsdf", mobile: "555-555-555", rewards: 22, email: "sdfsdfsdfs", membership: false, id: 14, }, ], 
orders: [ { id: 2, reference: "order-2-2-1-2", customerId: 2, 
				products: [ { id: 1, name: "Product HHYDP",  categoryId: 1, numInStock: 0, unitPrice: 18, }, { id: 2, name: "Product RECZE",  categoryId: 1, numInStock: 0, unitPrice: 19, }, ], 
				amount: 9.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 3, reference: "order-4-3-1-2", customerId: 4, 
				products: [ { id: 1, name: "Product HHYDP",  categoryId: 1, numInStock: 0, unitPrice: 18, }, { id: 2, name: "Product RECZE",  categoryId: 1, numInStock: 0, unitPrice: 19, }, ],
				amount: 5.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 4, reference: "order-4-4-1-2", customerId: 4, 
				products: [ { id: 3, name: "Product IMEHJ",  categoryId: 2, numInStock: 0, unitPrice: 10, }, { id: 4, name: "Product KSBRM",  categoryId: 2, numInStock: 0, unitPrice: 22, }, ], 
				amount: 499.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 5, reference: "order-5-5-1-2", customerId: 5, 
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 399.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 6, reference: "order-6-6-1-2", customerId: 6,
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 329.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 8, reference: "order-8-8-1-2", customerId: 8, 
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 89.99, orderDate: "2017-01-12", shippedDate: "2017-01-10", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 9, reference: "order-9-9-1-2", customerId: 9, 
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 59.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 10, reference: "order-10-10-1-2", customerId: 10, 
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 49.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 12, reference: "order-2-12-1-2", customerId: 2,
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 49.99, orderDate: "2017-01-01", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 14, reference: "order-2-14-1-2", customerId: 4,
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, ], 
				amount: 19.99, orderDate: "2017-01-09", shippedDate: "2017-01-01", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, }, 
			{ id: 15, reference: "order-11-15-1-2", customerId: 11, 
				products: [ { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 0, unitPrice: 21.5, }, { id: 19, name: "Product XKXDO",  categoryId: 3, numInStock: 0, unitPrice: 9.2, 
								category: { id: 3, name: "Confections", description: "Desserts, candies, and sweet breads", picture: null, }, text: "Product XKXDO", value: 19, }, ], 
				amount: 222, orderDate: "2017-01-19", shippedDate: "2017-01-16", shipAddress: { address: "Gran Vía, 0123", city: "Madrid", zipcode: "10298", country: "Spain", }, 
				quantity: 12, price: 33, }, 
			{ products: [ { id: 4, name: "Product KSBRM",  categoryId: 2, numInStock: 2, unitPrice: 22, 
				category: { id: 2, name: "Condiments", description: "Sweet and savory sauces, relishes, spreads, and seasonings", picture: null, }, text: "Product KSBRM", value: 4, }, 
				{ id: 6, name: "Product VAIIV",  categoryId: 2, numInStock: 0, unitPrice: 25, 
					category: { id: 2, name: "Condiments", description: "Sweet and savory sauces, relishes, spreads, and seasonings", picture: null, }, text: "Product VAIIV", value: 6, }, ],
					customerId: 4, orderDate: "2017-08-08", shippedDate: null, shipAddress: { address: "sss", city: "sss", zipcode: "sss", country: "sss", },
					reference: "ss-2-22-22", amount: 2323, id: 16, }, ], 
products: [ { id: 1, name: "Product HHYDP",  categoryId: 1, numInStock: 23, unitPrice: 18, }, 
                { id: 2, name: "Product RECZE",  categoryId: 1, numInStock: 10, unitPrice: 19, }, 
                { id: 3, name: "Product IMEHJ",  categoryId: 2, numInStock: 0, unitPrice: 10, }, 
                { id: 4, name: "Product KSBRM",  categoryId: 2, numInStock: 2, unitPrice: 22, }, 
                { id: 5, name: "Product EPEIM",  categoryId: 2, numInStock: 333, unitPrice: 21.5, }, 
                { id: 6, name: "Product VAIIV",  categoryId: 2, numInStock: 0, unitPrice: 25, }, 
                { id: 7, name: "Product HMLNI",  categoryId: 7, numInStock: 0, unitPrice: 30, }, 
                { id: 8, name: "Product WVJFP",  categoryId: 2, numInStock: 0, unitPrice: 40, }, 
                { id: 9, name: "Product AOZBW",  categoryId: 6, numInStock: 0, unitPrice: 97, }, 
                { id: 10, name: "Product YHXGE",  categoryId: 8, numInStock: 0, unitPrice: 31, },
                { id: 11, name: "Product QMVUN",  categoryId: 4, numInStock: 0, unitPrice: 21, }, 
                { id: 12, name: "Product OSFNS",  categoryId: 4, numInStock: 0, unitPrice: 38, },
                { id: 13, name: "Product POXFU",  categoryId: 8, numInStock: 0, unitPrice: 6, }, 
                { id: 14, name: "Product PWCJB",  categoryId: 7, numInStock: 0, unitPrice: 23.5, },
                { id: 15, name: "Product KSZOI",  categoryId: 2, numInStock: 33, unitPrice: 15.5, }, 
                { id: 16, name: "Product PAFRH",  categoryId: 3, numInStock: 0, unitPrice: 17.5, }, 
                { id: 17, name: "Product BLCAX",  categoryId: 6, numInStock: 0, unitPrice: 39, }, 
                { id: 18, name: "Product CKEDC",  categoryId: 8, numInStock: 0, unitPrice: 62.5, }, 
                { id: 19, name: "Product XKXDO",  categoryId: 3, numInStock: 0, unitPrice: 9.2, }, 
                { id: 20, name: "Product QHFFP",  categoryId: 3, numInStock: 23, unitPrice: 81, }, 
                { id: 21, name: "Product VJZZH",  categoryId: 3, numInStock: 0, unitPrice: 18, }, 
                { id: 22, name: "Product CPHFY",  categoryId: 5, numInStock: 0, unitPrice: 21, },
                { id: 23, name: "Product JLUDZ",  categoryId: 5, numInStock: 0, unitPrice: 9.5, }, 
                { id: 24, name: "Product QOGNU",  categoryId: 2, numInStock: 0, unitPrice: 4.5, },
                {  categoryId: 3, name: "Product ABCD", unitPrice: 222, numInStock: 23, id: 26, }, 
                { id: 27, name: "asdasd",  categoryId: 3, numInStock: "22", unitPrice: "234", }, ], 
// products:[  {id: 1, tpoCd:"A10100", tpoNm:"송파정보센터",      categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"A10100", useYn:"Y"},
//             {id: 2, tpoCd:"A10201", tpoNm:"과천",              categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A10100", useYn:"Y"},
//             {id: 3, tpoCd:"A10202", tpoNm:"강남정보센터",      categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"A10202", useYn:"Y"},
//             {id: 4, tpoCd:"A10C01", tpoNm:"강남 OST",          categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A10100", useYn:"Y"},
//             {id: 5, tpoCd:"A20100", tpoNm:"동작종합통신센터",  categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 6, tpoCd:"A20302", tpoNm:"영등포전송국사",     categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 7, tpoCd:"A20448", tpoNm:"강서전송국사",      categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 8, tpoCd:"A20702", tpoNm:"대전서중유성구HISP", categoryId:7, tpoTypeNm:"HFC국사", mgmtTpoCd:"F10100", useYn:"Y"},
//             {id: 9, tpoCd:"A20703", tpoNm:"서울강서HRO(삭제)", categoryId:7, tpoTypeNm:"HFC국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 10, tpoCd:"A20710", tpoNm:"서울동작HISP",      categoryId:7, tpoTypeNm:"HFC국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 11, tpoCd:"A20718", tpoNm:"서울강남HFC",       categoryId:7, tpoTypeNm:"HFC국사", mgmtTpoCd:"A10202", useYn:"Y"},
//             {id: 12, tpoCd:"A20D01", tpoNm:"보라매 SKT",        categoryId:8, tpoTypeNm:"SKT국사", mgmtTpoCd:"A20100", useYn:"Y"},
//             {id: 13, tpoCd:"A30100", tpoNm:"서대문정보센터",     categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"A30100", useYn:"Y"},
//             {id: 14, tpoCd:"A30302", tpoNm:"종로국사",          categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A30100", useYn:"Y"},
//             {id: 15, tpoCd:"A30E01", tpoNm:"강북 신세기",       categoryId:8, tpoTypeNm:"SKT국사", mgmtTpoCd:"A30100", useYn:"Y"},
//             {id: 16, tpoCd:"A40100", tpoNm:"성북정보센터",      categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"A40100", useYn:"Y"},
//             {id: 17, tpoCd:"A40201", tpoNm:"동대문",            categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A40100", useYn:"Y"},
//             {id: 18, tpoCd:"A40202", tpoNm:"노원",              categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"A40100", useYn:"Y"},
//             {id: 19, tpoCd:"A40D01", tpoNm:"장안SKT",           categoryId:8, tpoTypeNm:"SKT국사", mgmtTpoCd:"A40100", useYn:"Y"},
//             {id: 20, tpoCd:"B10100", tpoNm:"동부산정보센터",    categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"B10100", useYn:"Y"},
//             {id: 21, tpoCd:"B20100", tpoNm:"부산지사(연제)",    categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"B20100", useYn:"Y"},
//             {id: 22, tpoCd:"B20D01", tpoNm:"SKT부암국사",       categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"B20100", useYn:"Y"},
//             {id: 23, tpoCd:"C10100", tpoNm:"인천지사(남동)",    categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"C10100", useYn:"Y"},
//             {id: 24, tpoCd:"C10201", tpoNm:"연수전송집중국",    categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"C10100", useYn:"Y"},
//             {id: 25, tpoCd:"C10202", tpoNm:"부천전송집중국",    categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"C10100", useYn:"Y"},
//             {id: 26, tpoCd:"C20100", tpoNm:"계양정보센터",      categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"C20100", useYn:"Y"},
//             {id: 27, tpoCd:"D10100", tpoNm:"남울산정보센터",    categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"D10100", useYn:"Y"},
//             {id: 28, tpoCd:"D10201", tpoNm:"울산동구",          categoryId:2, tpoTypeNm:"전송국사", mgmtTpoCd:"D10100", useYn:"Y"},
//             {id: 29, tpoCd:"E10100", tpoNm:"대구/중",           categoryId:1, tpoTypeNm:"교환전송국사", mgmtTpoCd:"E10100", useYn:"Y"}, ],
categories: [ { id: 1, name: "Beverages", description: "Soft drinks, coffees, teas, beers, and ales", picture: null, }, 
			{ id: 2, name: "Condiments", description: "Sweet and savory sauces, relishes, spreads, and seasonings", picture: null, }, 
			{ id: 3, name: "Confections", description: "Desserts, candies, and sweet breads", picture: null, }, 
			{ id: 4, name: "Dairy Products", description: "Cheeses", picture: null, }, 
			{ id: 5, name: "Grains/Cereals", description: "Breads, crackers, pasta, and cereal", picture: null, }, 
			{ id: 6, name: "Meat/Poultry", description: "Prepared meats", picture: null, },
			{ id: 7, name: "Produce", description: "Dried fruit and bean curd", picture: null, }, 
            { id: 8, name: "Seafood", description: "Seaweed and fish", picture: null, }, ],
tpoCategories: [ { id: 1, name: "교환전송국사", description: "교환전송국사", picture: null, },
            { id: 2, name: "전송국사", description: "전송국사", picture: null, },
            { id: 4, name: "가입자국사", description: "가입자국사", picture: null, },
            { id: 7, name: "HFC국사", description: "HFC국사", picture: null, },
            { id: 3, name: "타사업국사", description: "타사업국사", picture: null, },
            { id: 5, name: "SKT국사", description: "SKT국사", picture: null, },
            { id: 6, name: "구내통신국사", description: "구내통신국사", picture: null, },
            { id: 8, name: "해외접속국사", description: "해외접속국사", picture: null, },
            { id: 9, name: "SO국사(TP)", description: "SO국사(TP)", picture: null, },
            { id: 10, name: "관리용국사", description: "관리용국사", picture: null, },
            { id: 11, name: "BcN국사", description: "BcN국사", picture: null, } ], }; 